mutation create_block($block_spec: jsonb) {
  insert_block(objects: { archived: false, type: "page", publicly_accessible: false, language_id: 1, topic_id: "13", block: $block_spec }) {
    affected_rows
    returning {
      block
      archived
      type
      created_time
      publicly_accessible
      id
      topic_id
      url
      votes {
        id
        user_id
        user_comment
      }
    }
  }
}
