mutation create_curriculum_with_topicLabels {
  insert_curriculum(
    objects: [
      {
        description: "Curriculum for Excellence places learners at the heart of education. At its centre are four fundamental capacities..."
        publicly_accessible: true
        short_title: "CFE"
        name: "Curriculum for Excellence"
        country_id: "1"
        institution_id: "1"
        topic_labels: {
          data: [
            { order_id: 1, title: "cfe_root" }
            { order_id: 2, title: "Subject Area" }
            { order_id: 3, title: "Benchmark" }
            { order_id: 4, title: "Curriculum organiser" }
            { order_id: 5, title: "Es and O" }
            { order_id: 6, title: "Support Benchmark" }
          ]
        }
      }
      {
        description: "The Scottish Qualifications Authority is the executive non-departmental public body of the Scottish Government responsible for accrediting educational awards..."
        publicly_accessible: true
        short_title: "SQA"
        name: "Scottish Qualifications Authority"
        country_id: "1"
        institution_id: "1"
        topic_labels: {
          data: [
            { order_id: 1, title: "sqa_root" }
            { order_id: 2, title: "Subject" }
            { order_id: 3, title: "Section" }
            { order_id: 4, title: "Part" }
            { order_id: 5, title: "Key Issue" }
            { order_id: 6, title: "Key Issue Explanation" }
          ]
        }
      }
    ]
  ) {
    affected_rows
    returning {
      id
      publicly_accessible
      description
      short_title
      name
      topic_labels {
        curriculum_id
        id
        order_id
        title
      }
    }
  }
}
