query get_all_curriculum_with_all_topics_for_defined_level_sequence($label_sequence: Int) {
  curriculum {
    has_public_access
    id
    short_title
    title
    institution {
      name
      id
    }
    topic_labels(where: { sequence: { _eq: $label_sequence } }) {
      sequence
      title
      id
      topics {
        label
        title
        has_children
        description
        parent_id
        id
        topic_unit_title
        topic_label_id
      }
    }
  }
}
