query get_all_curriculums_with_all_topic_labels_and_topics {
  curriculum {
    publicly_accessible
    id
    short_title
    name
    institution {
      name
      id
    }
    topic_labels {
      order_id
      title
      id
      topics {
        title
        has_children
        description
        parent_id
        id
        topic_unit_title
        topic_label_id
      }
    }
  }
}
