mutation create_countries {
  insert_country(objects: [{ code: "GBR", name: "United Kingdom" }, { code: "SWE", name: "Sweden" }]) {
    affected_rows
    returning {
      id
      code
      name
    }
  }
}
