mutation create_languages {
  insert_language(objects: [{ code: "EN", name: "English" }, { code: "SV", name: "Swedish" }]) {
    affected_rows
    returning {
      code
      name
      id
    }
  }
}
