mutation create_sqa_topic_for_topicLabel_seq_2 {
  insert_topic(
    objects: [
      {
        curriculum_id: "2"
        topic_label_id: "8"
        title: "NUMAERACY_AND_MATHEMATICS"
        topic_unit_title: "NUMAERACY_AND_MATHEMATICS-MATHEMATICS_SQA"
        description: "NUMAERACY_AND_MATHEMATICS-MATHEMATICS_SQA description"
        has_children: true
        label: "Subject"
        parent_id: "4"
      }
      {
        curriculum_id: "2"
        topic_label_id: "8"
        title: "SOCIAL_STUDIES"
        topic_unit_title: "SOCIAL_STUDIES-HISTORY_SQA"
        description: "SOCIAL_STUDIES-HISTORY_SQA description"
        has_children: false
        label: "Subject"
        parent_id: "5"
      }
      {
        curriculum_id: "2"
        topic_label_id: "8"
        title: "SOCIAL_STUDIES"
        topic_unit_title: "SOCIAL_STUDIES_CFE"
        description: "SOCIAL_STUDIES_CFE description"
        has_children: false
        label: "Subject"
        parent_id: "6"
      }
    ]
  ) {
    returning {
      curriculum {
        description
        has_public_access
      }
      description
      has_children
      id
      label
      parent_id
      same_as
      similar_to
      title
      curriculum_id
      topic_label {
        id
        sequence
        title
      }
    }
    affected_rows
  }
}
