mutation create_sqa_topic_for_topicLabel_seq_3 {
  insert_topic(
    objects: [
      {
        curriculum_id: "2"
        topic_label_id: "10"
        title: "AVD_HIGHER"
        topic_unit_title: "AVD_HIGHER#SQA"
        description: "AVD_HIGHER_SQA description"
        has_children: true
        parent_id: "1"
      }
      {
        curriculum_id: "2"
        topic_label_id: "2"
        title: "NATIONAL_5"
        topic_unit_title: "NATIONAL_5#History#SQA"
        description: "NATIONAL_5-History description"
        has_children: true
        parent_id: "2"
      }
      {
        curriculum_id: "2"
        topic_label_id: "2"
        title: "NATIONAL_5"
        topic_unit_title: "NATIONAL_5#Science#SQA"
        description: "NATIONAL_5-Science description"
        has_children: true
        parent_id: "3"
      }
    ]
  ) {
    returning {
      curriculum {
        description
        publicly_accessible
      }
      description
      has_children
      id

      parent_id
      identical_topics {
        id
        topic_id
        type
      }
      title
      curriculum_id
      topic_label {
        id
        order_id
        title
      }
    }
    affected_rows
  }
}
