mutation create_sqa_topic_for_topicLabel_seq_1 {
  insert_topic(
    objects: [
      { curriculum_id: "2", topic_label_id: "7", title: "MATHEMATICS", topic_unit_title: "MATHEMATICS#SQA", description: "MATHEMATICS_SQA description", has_children: true }
      { curriculum_id: "2", topic_label_id: "7", title: "HISTORY", topic_unit_title: "HISTORY_SQA", description: "HISTORY_SQA description", has_children: true }
      {
        curriculum_id: "2"
        topic_label_id: "7"
        title: "COMPUTER_SCIENCE"
        topic_unit_title: "COMPUTER_SCIENCE#SQA"
        description: "COMPUTER_SCIENCE_SQA description"
        has_children: true
      }
    ]
  ) {
    returning {
      curriculum {
        description
        publicly_accessible
      }
      description
      has_children
      id
      parent_id
      identical_topics {
        id
        topic_id
        type
      }
      title
      curriculum_id
      topic_label {
        id
        order_id
        title
      }
    }
    affected_rows
  }
}
