mutation create_sqa_topic_for_topicLabel_seq_3 {
  insert_topic(
    objects: [
      {
        curriculum_id: "1"
        topic_label_id: "10"
        title: "AVD_HIGHER"
        topic_unit_title: "AVD_HIGHER_SQA"
        description: "AVD_HIGHER_SQA description"
        has_children: true
        label: "Benchmark"
        parent_id: "1"
      }
      {
        curriculum_id: "1"
        topic_label_id: "2"
        title: "NATIONAL_5"
        topic_unit_title: "NATIONAL_5-History"
        description: "NATIONAL_5-History description"
        has_children: true
        label: "Section"
        parent_id: "2"
      }
      {
        curriculum_id: "1"
        topic_label_id: "2"
        title: "NATIONAL_5"
        topic_unit_title: "NATIONAL_5-Science"
        description: "NATIONAL_5-Science description"
        has_children: true
        label: "Section"
        parent_id: "3"
      }
    ]
  ) {
    returning {
      curriculum {
        description
        has_public_access
      }
      description
      has_children
      id
      label
      parent_id
      same_as
      similar_to
      title
      curriculum_id
      topic_label {
        id
        sequence
        title
      }
    }
    affected_rows
  }
}
