mutation create_topic_for_fourth_topicLabel {
  insert_topic(
    objects: [
      {
        curriculum_id: "1"
        topic_label_id: "4"
        title: "Circles"
        topic_unit_title: "Circles-Statistics-NATIONAL_5-Maths"
        description: "Circles-Statistics-NATIONAL_5-Maths description"
        has_children: false
        label: "Key Issues"
        parent_id: "9"
      }
      {
        curriculum_id: "1"
        topic_label_id: "4"
        title: "Pythagoras"
        topic_unit_title: "Pythagoras-Statistics-NATIONAL_5-Maths"
        description: "Pythagoras-Statistics-NATIONAL_5-Maths description"
        has_children: false
        label: "Key Issues"
        parent_id: "11"
      }
    ]
  ) {
    returning {
      curriculum {
        description
        has_public_access
      }
      description
      has_children
      id
      label
      parent_id
      same_as
      similar_to
      title
      curriculum_id
      topic_label {
        id
        sequence
        title
      }
    }
    affected_rows
  }
}
