mutation create_curriculum_with_topicLabels {
  insert_curriculum(
    objects: {
      description: "Curriculum description"
      has_public_access: true
      short_title: "CFE"
      title: "Curriculum for Excellence"
      topic_labels: { data: [{ sequence: 1, title: "Subject" }, { sequence: 2, title: "Section" }, { sequence: 3, title: "Parts" }, { sequence: 4, title: "Key Issues" }] }
    }
  ) {
    returning {
      id
      has_public_access
      description
      short_title
      title
      topic_labels {
        curriculum_id
        id
        sequence
        title
      }
      ref_curriculum_id
    }
  }
}
