mutation create_cfe_topic_for_topicLabel_seq_2 {
  insert_topic(
    objects: [
      {
        curriculum_id: "1"
        topic_label_id: "2"
        title: "Numaeracy and Mathematics"
        topic_unit_title: "NUMAERACY_AND_MATHEMATICS#MATHEMATICS#CFE"
        description: "NUMAERACY_AND_MATHEMATICS-MATHEMATICS-CFE description"
        has_children: true
        label: "Subject Area"
        parent_id: "1"
      }
      {
        curriculum_id: "1"
        topic_label_id: "2"
        title: "Social Studies"
        topic_unit_title: "SOCIAL_STUDIES#HISTORY#CFE"
        description: "SOCIAL_STUDIES-HISTORY-CFE description"
        has_children: false
        label: "Subject Area"
        parent_id: "2"
      }
      {
        curriculum_id: "1"
        topic_label_id: "2"
        title: "Social Science"
        topic_unit_title: "SOCIAL_SCIENCE#SCIENCE#CFE"
        description: "SOCIAL_SCIENCE-SCIENCE-CFE description"
        has_children: false
        label: "Subject Area"
        parent_id: "3"
      }
    ]
  ) {
    returning {
      curriculum {
        description
        has_public_access
      }
      description
      has_children
      id
      label
      parent_id
      same_as
      similar_to
      title
      curriculum_id
      topic_label {
        id
        sequence
        title
      }
    }
    affected_rows
  }
}
