mutation create_cfe_topic_for_topicLabel_seq_1 {
  insert_topic(
    objects: [
      { curriculum_id: "1", topic_label_id: "1", title: "Mathematics", topic_unit_title: "MATHEMATICS#CFE", description: "MATHEMATICS-CFE description", has_children: true }
      { curriculum_id: "1", topic_label_id: "1", title: "History", topic_unit_title: "HISTORY#CFE", description: "HISTORY-CFE description", has_children: true }
      { curriculum_id: "1", topic_label_id: "1", title: "Science", topic_unit_title: "SCIENCE#CFE", description: "SCIENCE-CFE description", has_children: true }
    ]
  ) {
    returning {
      curriculum {
        description
        publicly_accessible
      }
      description
      has_children
      id
      parent_id
      identical_topics {
        id
        topic_id
        type
      }

      title
      curriculum_id
      topic_label {
        id
        order_id
        title
      }
    }
    affected_rows
  }
}
